### ISSUE TITLE
move prater config to the goerli repository

### ISSUE THREAD

**Issue by q9f** [eth-clients/eth2-networks#76]
if nobody disagrees, I would like to move the prater config to the stand-alone goerli repository:

* https://github.com/eth-clients/goerli (formerly https://github.com/goerli/testnet)

the rationale is that the merge is not only technical but also logical. also, long-standing testnets should have their dedicated home.

edit: here https://github.com/eth-clients/goerli/tree/main/prater

**Comment by ajsutton** [comment]
I'm not strongly opinionated about it, but I am finding it incredibly useful to have a central place for network configs to save having to go hunting around the Internet for them all the time.

Also worth noting that Teku pulls the genesis state from GitHub - it's for a specific commit hash so should keep working even if we move things around but definitely would be good to keep it working.

**Comment by tersec** [comment]
Nimbus likewise pulls its Prater definition directly from `merge-testnets` automatically, and it's quite convenient to have that centralized place.

**Comment by q9f** [comment]
Is that a good idea to pull this from Github?

So if I modify the config right now it would break both of your clients?

**Comment by arnetheduck** [comment]
> Is that a good idea to pull this from Github?

in nimbus, we lock it down with a submodule, so no unaudited edits will make it to the client proper until our say-so (we use submodules for all dependencies, this is just one more)

**Comment by ajsutton** [comment]
In Teku we refer to only the genesis file and include the commit hash in the URL so it shouldn't be changeable.  We only do this for testnets (MainNet genesis is included directly in teku source and distributions).  Referring to GitHub saves bloating the distribution with the genesis for every testnet we need to support and being a testnet the impact of something going wrong with it is minimal.

But primarily my comment was that it's really useful to have the configs in one place instead of scattered everywhere. I don't think I've seen any actual reason for moving the config and changing a system that has been working very well so far.

**Comment by ajsutton** [comment]
I also don't think moving will actually break the URLs btw, GitHub is generally good with redirects, I'm just pointing it out as something worth testing to avoid fun surprises.

**Comment by q9f** [comment]
> But primarily my comment was that it's really useful to have the configs in one place instead of scattered everywhere. I don't think I've seen any actual reason for moving the config and changing a system that has been working very well so far.

Yes, however, we are leaving the era of 12 devnets per year and entering the long-standing, public-facing networks chapter. I don't mind adding more merge testnets or other ad-hoc networks here. But beyond the needs of client teams, there is also a community around public-facing testnets.

But it's really not important. I just wanted to avoid that we have to maintain the spec in multiple locations.
